name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: ./build
    steps:
    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1
      
    - name: Install packages
      run: |
        apk add git make cmake libstdc++ gcc g++ libuv-dev openssl-dev hwloc-dev
      shell: alpine.sh --root {0}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Create directory
      run: mkdir build
      shell: alpine.sh --root {0}

    - name: Configure build
      working-directory: ${{env.working-dir}}
      run: cmake ..
      shell: alpine.sh --root {0}

    - name: Build
      working-directory: ${{env.working-dir}}
      run: make -j 6
      shell: alpine.sh --root {0}

    - name: Make executable
      working-directory: ${{env.working-dir}}
      run: chmod u+x ./xmrig
      shell: alpine.sh --root {0}

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: xmrig
        path: build/xmrig

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/xmrig
