name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: ./build
    steps:
    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1
      with:
        packages: >
          make
          cmake
          libstdc++
          gcc
          g++
          automake
          libtool
          autoconf
          linux-headers

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        mkdir build
        cd ./scripts
        ./build_deps.sh
        cd ../build
        cmake .. -DXMRIG_DEPS=scripts/deps -DBUILD_STATIC=ON
        make -j 6
        chmod u+x ./xmrig
      shell: alpine.sh --root {0}

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: xmrig
        path: build/xmrig

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/xmrig
